# Makefile
# 10 january 2001

include ../make.common

#all: $(COMMON_OBJS)

common.so: ../make.common Makefile common.c ../include/common.h

socket.so: ../make.common Makefile _socket.c ../include/_socket.h

clean: 
#	rm -f $(COMMON_OBJS)
